### ISSUE TITLE
a11y related - home page links are unclear

### ISSUE THREAD

**Issue by jefflembeck** [npm/newww#1069]
From tota11y

The home page has a big list of packages people use npm for consistently - those packages have html structured like so:

```
<a class="package-logo" href="/package/express">
    <img src="https://cldup.com/wpGXm1cWwB.png" alt="express logo">
</a>
```

which means links that are missing -

we should make it more like:
```html
<a class="package-logo" href="/package/express">
    <span class="a11y-only">Express</span>
    <img src="https://cldup.com/wpGXm1cWwB.png" alt="express logo">
</a>
```

with css like:
```css
.a11y-only {
	position: absolute !important;
	height: 1px;
	width: 1px;
	overflow: hidden;
	clip: rect(1px 1px 1px 1px); /* IE6, IE7 */
	clip: rect(1px, 1px, 1px, 1px);
}
```
