### ISSUE TITLE
<thead> is `display: none` by default

### ISSUE THREAD

**Issue by woollybogger** [npm/newww#908]
Production `index.css` has the following rule:

```css
table thead {
  display: none;
}
```

This is causing the headers of tables generated by markdown to be hidden, such as the parameter tables in the docs for my package [here](https://www.npmjs.com/package/pro-array#Array#each..eachCallback).
